source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

target 'PhotoSafer' do
  pod 'Lynx', '3.4.0', :subspecs => [
    'Framework',
  ]

  pod 'PrimJS', '2.14.0-rc.1', :subspecs => ['quickjs', 'napi']

  # integrate image-service, log-service, and http-service
  pod 'LynxService', '3.4.0', :subspecs => [
      'Image',
      'Log',
      'Http',
  ]

  # ImageService
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'

  pod 'XElement', '3.4.0'
end